export const months = [
  { id: 1, value: 'January', month: 'January' },
  { id: 2, value: 'February', month: 'February' },
  { id: 3, value: 'March', month: 'March' },
  { id: 4, value: 'April', month: 'April' },
  { id: 5, value: 'May', month: 'May' },
  { id: 6, value: 'June', month: 'June' },
  { id: 7, value: 'July', month: 'July' },
  { id: 8, value: 'August', month: 'August' },
  { id: 9, value: 'September', month: 'September' },
  { id: 10, value: 'October', month: 'October' },
  { id: 11, value: 'November', month: 'November' },
  { id: 12, value: 'December', month: 'December' },
];

export const fakeData = [
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'January',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'January',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'February',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'February',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'March',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'March',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'April',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'April',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'May',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'May',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'June',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'June',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'July',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'July',
  },
  {
    grateful: 'family',
    challenge: 'no time',
    developing: 'care alot about my social life',
    time: '07:00',
    date: 'September',
  },
];
